name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: read

jobs:
  build:
    name: Build wheels and source distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install build dependencies
        run: python -m pip install --upgrade build

      - name: Build source distribution
        run: python -m build

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: dist/*
          if-no-files-found: error

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: dist

      - name: Push build artifacts to PyPI
        uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          skip_existing: true
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
